require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AboutsController do

  def mock_about(stubs={})
    @mock_about ||= mock_model(About, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all abouts as @abouts" do
      About.stub(:all) { [mock_about] }
      get :index
      assigns(:abouts).should eq([mock_about])
    end
  end

  describe "GET show" do
    it "assigns the requested about as @about" do
      About.stub(:find).with("37") { mock_about }
      get :show, :id => "37"
      assigns(:about).should be(mock_about)
    end
  end

  describe "GET new" do
    it "assigns a new about as @about" do
      About.stub(:new) { mock_about }
      get :new
      assigns(:about).should be(mock_about)
    end
  end

  describe "GET edit" do
    it "assigns the requested about as @about" do
      About.stub(:find).with("37") { mock_about }
      get :edit, :id => "37"
      assigns(:about).should be(mock_about)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created about as @about" do
        About.stub(:new).with({'these' => 'params'}) { mock_about(:save => true) }
        post :create, :about => {'these' => 'params'}
        assigns(:about).should be(mock_about)
      end

      it "redirects to the created about" do
        About.stub(:new) { mock_about(:save => true) }
        post :create, :about => {}
        response.should redirect_to(about_url(mock_about))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved about as @about" do
        About.stub(:new).with({'these' => 'params'}) { mock_about(:save => false) }
        post :create, :about => {'these' => 'params'}
        assigns(:about).should be(mock_about)
      end

      it "re-renders the 'new' template" do
        About.stub(:new) { mock_about(:save => false) }
        post :create, :about => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested about" do
        About.stub(:find).with("37") { mock_about }
        mock_about.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :about => {'these' => 'params'}
      end

      it "assigns the requested about as @about" do
        About.stub(:find) { mock_about(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:about).should be(mock_about)
      end

      it "redirects to the about" do
        About.stub(:find) { mock_about(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(about_url(mock_about))
      end
    end

    describe "with invalid params" do
      it "assigns the about as @about" do
        About.stub(:find) { mock_about(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:about).should be(mock_about)
      end

      it "re-renders the 'edit' template" do
        About.stub(:find) { mock_about(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested about" do
      About.stub(:find).with("37") { mock_about }
      mock_about.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the abouts list" do
      About.stub(:find) { mock_about }
      delete :destroy, :id => "1"
      response.should redirect_to(abouts_url)
    end
  end

end
