require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AlbumCategoriesController do

  def mock_album_category(stubs={})
    @mock_album_category ||= mock_model(AlbumCategory, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all album_categories as @album_categories" do
      AlbumCategory.stub(:all) { [mock_album_category] }
      get :index
      assigns(:album_categories).should eq([mock_album_category])
    end
  end

  describe "GET show" do
    it "assigns the requested album_category as @album_category" do
      AlbumCategory.stub(:find).with("37") { mock_album_category }
      get :show, :id => "37"
      assigns(:album_category).should be(mock_album_category)
    end
  end

  describe "GET new" do
    it "assigns a new album_category as @album_category" do
      AlbumCategory.stub(:new) { mock_album_category }
      get :new
      assigns(:album_category).should be(mock_album_category)
    end
  end

  describe "GET edit" do
    it "assigns the requested album_category as @album_category" do
      AlbumCategory.stub(:find).with("37") { mock_album_category }
      get :edit, :id => "37"
      assigns(:album_category).should be(mock_album_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created album_category as @album_category" do
        AlbumCategory.stub(:new).with({'these' => 'params'}) { mock_album_category(:save => true) }
        post :create, :album_category => {'these' => 'params'}
        assigns(:album_category).should be(mock_album_category)
      end

      it "redirects to the created album_category" do
        AlbumCategory.stub(:new) { mock_album_category(:save => true) }
        post :create, :album_category => {}
        response.should redirect_to(album_category_url(mock_album_category))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved album_category as @album_category" do
        AlbumCategory.stub(:new).with({'these' => 'params'}) { mock_album_category(:save => false) }
        post :create, :album_category => {'these' => 'params'}
        assigns(:album_category).should be(mock_album_category)
      end

      it "re-renders the 'new' template" do
        AlbumCategory.stub(:new) { mock_album_category(:save => false) }
        post :create, :album_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested album_category" do
        AlbumCategory.stub(:find).with("37") { mock_album_category }
        mock_album_category.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :album_category => {'these' => 'params'}
      end

      it "assigns the requested album_category as @album_category" do
        AlbumCategory.stub(:find) { mock_album_category(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:album_category).should be(mock_album_category)
      end

      it "redirects to the album_category" do
        AlbumCategory.stub(:find) { mock_album_category(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(album_category_url(mock_album_category))
      end
    end

    describe "with invalid params" do
      it "assigns the album_category as @album_category" do
        AlbumCategory.stub(:find) { mock_album_category(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:album_category).should be(mock_album_category)
      end

      it "re-renders the 'edit' template" do
        AlbumCategory.stub(:find) { mock_album_category(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested album_category" do
      AlbumCategory.stub(:find).with("37") { mock_album_category }
      mock_album_category.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the album_categories list" do
      AlbumCategory.stub(:find) { mock_album_category }
      delete :destroy, :id => "1"
      response.should redirect_to(album_categories_url)
    end
  end

end
