require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe InstrumentsController do

  def mock_instrument(stubs={})
    @mock_instrument ||= mock_model(Instrument, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all instruments as @instruments" do
      Instrument.stub(:all) { [mock_instrument] }
      get :index
      assigns(:instruments).should eq([mock_instrument])
    end
  end

  describe "GET show" do
    it "assigns the requested instrument as @instrument" do
      Instrument.stub(:find).with("37") { mock_instrument }
      get :show, :id => "37"
      assigns(:instrument).should be(mock_instrument)
    end
  end

  describe "GET new" do
    it "assigns a new instrument as @instrument" do
      Instrument.stub(:new) { mock_instrument }
      get :new
      assigns(:instrument).should be(mock_instrument)
    end
  end

  describe "GET edit" do
    it "assigns the requested instrument as @instrument" do
      Instrument.stub(:find).with("37") { mock_instrument }
      get :edit, :id => "37"
      assigns(:instrument).should be(mock_instrument)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created instrument as @instrument" do
        Instrument.stub(:new).with({'these' => 'params'}) { mock_instrument(:save => true) }
        post :create, :instrument => {'these' => 'params'}
        assigns(:instrument).should be(mock_instrument)
      end

      it "redirects to the created instrument" do
        Instrument.stub(:new) { mock_instrument(:save => true) }
        post :create, :instrument => {}
        response.should redirect_to(instrument_url(mock_instrument))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instrument as @instrument" do
        Instrument.stub(:new).with({'these' => 'params'}) { mock_instrument(:save => false) }
        post :create, :instrument => {'these' => 'params'}
        assigns(:instrument).should be(mock_instrument)
      end

      it "re-renders the 'new' template" do
        Instrument.stub(:new) { mock_instrument(:save => false) }
        post :create, :instrument => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instrument" do
        Instrument.stub(:find).with("37") { mock_instrument }
        mock_instrument.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :instrument => {'these' => 'params'}
      end

      it "assigns the requested instrument as @instrument" do
        Instrument.stub(:find) { mock_instrument(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:instrument).should be(mock_instrument)
      end

      it "redirects to the instrument" do
        Instrument.stub(:find) { mock_instrument(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(instrument_url(mock_instrument))
      end
    end

    describe "with invalid params" do
      it "assigns the instrument as @instrument" do
        Instrument.stub(:find) { mock_instrument(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:instrument).should be(mock_instrument)
      end

      it "re-renders the 'edit' template" do
        Instrument.stub(:find) { mock_instrument(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instrument" do
      Instrument.stub(:find).with("37") { mock_instrument }
      mock_instrument.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the instruments list" do
      Instrument.stub(:find) { mock_instrument }
      delete :destroy, :id => "1"
      response.should redirect_to(instruments_url)
    end
  end

end
