require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LocationSectionsController do

  def mock_location_section(stubs={})
    @mock_location_section ||= mock_model(LocationSection, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all location_sections as @location_sections" do
      LocationSection.stub(:all) { [mock_location_section] }
      get :index
      assigns(:location_sections).should eq([mock_location_section])
    end
  end

  describe "GET show" do
    it "assigns the requested location_section as @location_section" do
      LocationSection.stub(:find).with("37") { mock_location_section }
      get :show, :id => "37"
      assigns(:location_section).should be(mock_location_section)
    end
  end

  describe "GET new" do
    it "assigns a new location_section as @location_section" do
      LocationSection.stub(:new) { mock_location_section }
      get :new
      assigns(:location_section).should be(mock_location_section)
    end
  end

  describe "GET edit" do
    it "assigns the requested location_section as @location_section" do
      LocationSection.stub(:find).with("37") { mock_location_section }
      get :edit, :id => "37"
      assigns(:location_section).should be(mock_location_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created location_section as @location_section" do
        LocationSection.stub(:new).with({'these' => 'params'}) { mock_location_section(:save => true) }
        post :create, :location_section => {'these' => 'params'}
        assigns(:location_section).should be(mock_location_section)
      end

      it "redirects to the created location_section" do
        LocationSection.stub(:new) { mock_location_section(:save => true) }
        post :create, :location_section => {}
        response.should redirect_to(location_section_url(mock_location_section))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved location_section as @location_section" do
        LocationSection.stub(:new).with({'these' => 'params'}) { mock_location_section(:save => false) }
        post :create, :location_section => {'these' => 'params'}
        assigns(:location_section).should be(mock_location_section)
      end

      it "re-renders the 'new' template" do
        LocationSection.stub(:new) { mock_location_section(:save => false) }
        post :create, :location_section => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested location_section" do
        LocationSection.stub(:find).with("37") { mock_location_section }
        mock_location_section.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :location_section => {'these' => 'params'}
      end

      it "assigns the requested location_section as @location_section" do
        LocationSection.stub(:find) { mock_location_section(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:location_section).should be(mock_location_section)
      end

      it "redirects to the location_section" do
        LocationSection.stub(:find) { mock_location_section(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(location_section_url(mock_location_section))
      end
    end

    describe "with invalid params" do
      it "assigns the location_section as @location_section" do
        LocationSection.stub(:find) { mock_location_section(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:location_section).should be(mock_location_section)
      end

      it "re-renders the 'edit' template" do
        LocationSection.stub(:find) { mock_location_section(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested location_section" do
      LocationSection.stub(:find).with("37") { mock_location_section }
      mock_location_section.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the location_sections list" do
      LocationSection.stub(:find) { mock_location_section }
      delete :destroy, :id => "1"
      response.should redirect_to(location_sections_url)
    end
  end

end
