require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MentorsController do

  def mock_mentor(stubs={})
    @mock_mentor ||= mock_model(Mentor, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all mentors as @mentors" do
      Mentor.stub(:all) { [mock_mentor] }
      get :index
      assigns(:mentors).should eq([mock_mentor])
    end
  end

  describe "GET show" do
    it "assigns the requested mentor as @mentor" do
      Mentor.stub(:find).with("37") { mock_mentor }
      get :show, :id => "37"
      assigns(:mentor).should be(mock_mentor)
    end
  end

  describe "GET new" do
    it "assigns a new mentor as @mentor" do
      Mentor.stub(:new) { mock_mentor }
      get :new
      assigns(:mentor).should be(mock_mentor)
    end
  end

  describe "GET edit" do
    it "assigns the requested mentor as @mentor" do
      Mentor.stub(:find).with("37") { mock_mentor }
      get :edit, :id => "37"
      assigns(:mentor).should be(mock_mentor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created mentor as @mentor" do
        Mentor.stub(:new).with({'these' => 'params'}) { mock_mentor(:save => true) }
        post :create, :mentor => {'these' => 'params'}
        assigns(:mentor).should be(mock_mentor)
      end

      it "redirects to the created mentor" do
        Mentor.stub(:new) { mock_mentor(:save => true) }
        post :create, :mentor => {}
        response.should redirect_to(mentor_url(mock_mentor))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mentor as @mentor" do
        Mentor.stub(:new).with({'these' => 'params'}) { mock_mentor(:save => false) }
        post :create, :mentor => {'these' => 'params'}
        assigns(:mentor).should be(mock_mentor)
      end

      it "re-renders the 'new' template" do
        Mentor.stub(:new) { mock_mentor(:save => false) }
        post :create, :mentor => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mentor" do
        Mentor.stub(:find).with("37") { mock_mentor }
        mock_mentor.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :mentor => {'these' => 'params'}
      end

      it "assigns the requested mentor as @mentor" do
        Mentor.stub(:find) { mock_mentor(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:mentor).should be(mock_mentor)
      end

      it "redirects to the mentor" do
        Mentor.stub(:find) { mock_mentor(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(mentor_url(mock_mentor))
      end
    end

    describe "with invalid params" do
      it "assigns the mentor as @mentor" do
        Mentor.stub(:find) { mock_mentor(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:mentor).should be(mock_mentor)
      end

      it "re-renders the 'edit' template" do
        Mentor.stub(:find) { mock_mentor(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mentor" do
      Mentor.stub(:find).with("37") { mock_mentor }
      mock_mentor.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the mentors list" do
      Mentor.stub(:find) { mock_mentor }
      delete :destroy, :id => "1"
      response.should redirect_to(mentors_url)
    end
  end

end
