require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ShopAdvicesController do

  def mock_shop_advice(stubs={})
    @mock_shop_advice ||= mock_model(ShopAdvice, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all shop_advices as @shop_advices" do
      ShopAdvice.stub(:all) { [mock_shop_advice] }
      get :index
      assigns(:shop_advices).should eq([mock_shop_advice])
    end
  end

  describe "GET show" do
    it "assigns the requested shop_advice as @shop_advice" do
      ShopAdvice.stub(:find).with("37") { mock_shop_advice }
      get :show, :id => "37"
      assigns(:shop_advice).should be(mock_shop_advice)
    end
  end

  describe "GET new" do
    it "assigns a new shop_advice as @shop_advice" do
      ShopAdvice.stub(:new) { mock_shop_advice }
      get :new
      assigns(:shop_advice).should be(mock_shop_advice)
    end
  end

  describe "GET edit" do
    it "assigns the requested shop_advice as @shop_advice" do
      ShopAdvice.stub(:find).with("37") { mock_shop_advice }
      get :edit, :id => "37"
      assigns(:shop_advice).should be(mock_shop_advice)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created shop_advice as @shop_advice" do
        ShopAdvice.stub(:new).with({'these' => 'params'}) { mock_shop_advice(:save => true) }
        post :create, :shop_advice => {'these' => 'params'}
        assigns(:shop_advice).should be(mock_shop_advice)
      end

      it "redirects to the created shop_advice" do
        ShopAdvice.stub(:new) { mock_shop_advice(:save => true) }
        post :create, :shop_advice => {}
        response.should redirect_to(shop_advice_url(mock_shop_advice))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shop_advice as @shop_advice" do
        ShopAdvice.stub(:new).with({'these' => 'params'}) { mock_shop_advice(:save => false) }
        post :create, :shop_advice => {'these' => 'params'}
        assigns(:shop_advice).should be(mock_shop_advice)
      end

      it "re-renders the 'new' template" do
        ShopAdvice.stub(:new) { mock_shop_advice(:save => false) }
        post :create, :shop_advice => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shop_advice" do
        ShopAdvice.stub(:find).with("37") { mock_shop_advice }
        mock_shop_advice.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :shop_advice => {'these' => 'params'}
      end

      it "assigns the requested shop_advice as @shop_advice" do
        ShopAdvice.stub(:find) { mock_shop_advice(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:shop_advice).should be(mock_shop_advice)
      end

      it "redirects to the shop_advice" do
        ShopAdvice.stub(:find) { mock_shop_advice(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(shop_advice_url(mock_shop_advice))
      end
    end

    describe "with invalid params" do
      it "assigns the shop_advice as @shop_advice" do
        ShopAdvice.stub(:find) { mock_shop_advice(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:shop_advice).should be(mock_shop_advice)
      end

      it "re-renders the 'edit' template" do
        ShopAdvice.stub(:find) { mock_shop_advice(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shop_advice" do
      ShopAdvice.stub(:find).with("37") { mock_shop_advice }
      mock_shop_advice.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the shop_advices list" do
      ShopAdvice.stub(:find) { mock_shop_advice }
      delete :destroy, :id => "1"
      response.should redirect_to(shop_advices_url)
    end
  end

end
